trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- script: |
    set -eux  # fail on error
    pip install exdown 
    pip install presidio-analyzer
    pip install presidio-anonymizer
    pip install presidio-image-redactor
    pip install jupyter
    pip install nbconvert
  
- script: |
    for f in docs/samples/python/*.ipynb;
    do;    
      jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=60 --output out_file $f;
    done;
  displayName: Execute notebooks
  continueOnError: true

- task: PythonScript@0
  displayName: 'Test python code in markdown files'
  continueOnError: true
  inputs:
    scriptSource: 'filePath'
    scriptPath: './.pipelines/templates/test-md.py'  