trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- script: |
    set -eux  # fail on error
    pip install exdown 
    pip install presidio-analyzer
    pip install presidio-anonymizer
    pip install presidio-image-redactor 
  
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './pipelines/templates/test-md.py'